### PR TITLE
Write name of all variables and methodes in python(snake_case).

### PR DESCRIPTION
**Pull request by PraddyumnYadav**
# What Have i done in this PullRequest.

- [x]  Formatted The Code
- [x]  Add .vscode/ in .gitignore
- [x]  Write All Public Variables and methodes in python(snake_case).

So This Was The Things That i Have Done in This Pull Request.
If You Have any Suggetions for me about this code then fell free to tell me that.
**Thank You**

### CODE REVIEW

**Comment by KiranSatyaRaj** [comment]
Thank you so much for contributing, did you run it @PraddyumnYadav?

**Comment by PraddyumnYadav** [comment]
After Running it there was a tkinter window in which there was a grid and when I closed it there was a closing message in the terminal.

**Comment by PraddyumnYadav** [comment]
Can you please send me image of that so I could understand that.

**Comment by KiranSatyaRaj** [comment]
> Can you please send me image of that so I could understand that.

Screenshot from 2023-01-16 18-53-07
Screenshot from 2023-01-16 21-51-49

**Comment by PraddyumnYadav** [comment]
Yes it was same like that

**Comment by PraddyumnYadav** [comment]
But in terminal it printed ran 0 tests in 0.000s

**Comment by PraddyumnYadav** [comment]
It Gives me this if i run **tests.py**
test.py running screenshot

**Comment by PraddyumnYadav** [comment]
Sorry i have done something wrong but i will fix it till tommorow.

**Comment by KiranSatyaRaj** [comment]
> It Gives me this if i run **tests.py**
> test.py running screenshot

that looks good to me.

**Pull request closed without merging**
