### PR TITLE
Name all the Variables and Methodes in python(snake_case).

### PR DESCRIPTION
**Pull request by PraddyumnYadav**
# What i Have done in this Pull Request

- [x]  Added .vscode/ in gitignore.
- [x]  Formatted all the Python Code.
- [x]  Name all the variables and methode according to python(snake_case).

So This Was The Things That i Have Done in This Pull Request.
If You Have any Suggetions for me about this code then fell free to tell me that.
**Thank You**

### CODE REVIEW

**Comment by KiranSatyaRaj** [comment]
If you're okay with the changes I proposed, you can go ahead and incorporate those changes or you can allow me to edit the necessary files, and merge the pull request right away, @PraddyumnYadav

**Comment by PraddyumnYadav** [comment]
Can you please tell me that How can I give you read and write information in this pull request Mr.Kiran

**Comment by KiranSatyaRaj** [comment]
> Can you please tell me that How can I give you read and write information in this pull request Mr.Kiran

It's already given, I can edit the files but I'm asking you if I can go ahead with that, and you can call me just kiran

**Comment by KiranSatyaRaj** [comment]
> You can edit thease files but please tell me what was the change and why you make it so that I can learn and try to not repeat those mistakes.

the changes are pretty minimal, here's what I'm changing here, on line 22 of graphics.py `print("window closed...")` and line 40, 41, 42 of the same file, `def __init__(self, point1, point2):, self._point1 = point1, self._point2 = point2` since the underscores are for data members of a class, only these and the rest looks good to me, I've run the program with this changes and it's working fine.

**Review by KiranSatyaRaj — APPROVED** [review]

**Pull request merged**
